// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef UI_LAUNCH_H
#define UI_LAUNCH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Launch
extern void ui_Launch_screen_init(void);
extern void ui_Launch_screen_destroy(void);
extern lv_obj_t * ui_Launch;
extern lv_obj_t * ui_TabDesktop;
extern lv_obj_t * ui_TabControlPad;
extern lv_obj_t * ui_wifiButton;
extern lv_obj_t * ui_bleButton;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_ButtonAutoScreenOff;
extern lv_obj_t * ui_TabHome;
extern lv_obj_t * ui_mainTimeLabel;
extern lv_obj_t * ui_weekdayLabel;
extern lv_obj_t * ui_weatherLabel2;
extern lv_obj_t * ui_tempLabel;
extern lv_obj_t * ui_dataLabel;
extern lv_obj_t * ui_TabAPP;
extern lv_obj_t * ui_ImgStateBar;
extern lv_obj_t * ui_timeLabel;
extern lv_obj_t * ui_batteryIMG;
extern lv_obj_t * ui_BatteryBar;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

