// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#include "../ui.h"

lv_obj_t * ui_Launch = NULL;
lv_obj_t * ui_TabDesktop = NULL;
lv_obj_t * ui_TabControlPad = NULL;
lv_obj_t * ui_wifiButton = NULL;
lv_obj_t * ui_bleButton = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_ButtonAutoScreenOff = NULL;
lv_obj_t * ui_TabHome = NULL;
lv_obj_t * ui_mainTimeLabel = NULL;
lv_obj_t * ui_weekdayLabel = NULL;
lv_obj_t * ui_weatherLabel2 = NULL;
lv_obj_t * ui_tempLabel = NULL;
lv_obj_t * ui_dataLabel = NULL;
lv_obj_t * ui_TabAPP = NULL;
lv_obj_t * ui_ImgStateBar = NULL;
lv_obj_t * ui_timeLabel = NULL;
lv_obj_t * ui_batteryIMG = NULL;
lv_obj_t * ui_BatteryBar = NULL;




// event funtions
void ui_event_ButtonAutoScreenOff(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_ButtonAutoScreenOff, LV_STATE_CHECKED, _UI_MODIFY_STATE_TOGGLE);
    }
}


// build funtions

void ui_Launch_screen_init(void)
{
    ui_Launch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Launch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabDesktop = lv_tabview_create(ui_Launch, LV_DIR_TOP, 0);
    lv_obj_set_width(ui_TabDesktop, 360);
    lv_obj_set_height(ui_TabDesktop, 360);
    lv_obj_set_align(ui_TabDesktop, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TabDesktop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabControlPad = lv_tabview_add_tab(ui_TabDesktop, "ControlPad");
    lv_obj_set_style_bg_img_src(ui_TabControlPad, &ui_img_backgroundimg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiButton = lv_btn_create(ui_TabControlPad);
    lv_obj_set_width(ui_wifiButton, 250);
    lv_obj_set_height(ui_wifiButton, 60);
    lv_obj_set_x(ui_wifiButton, 0);
    lv_obj_set_y(ui_wifiButton, -100);
    lv_obj_set_align(ui_wifiButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_wifiButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_wifiButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiButton, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifiButton, &ui_img_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifiButton, lv_color_hex(0x064E00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_wifiButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_wifiButton, lv_color_hex(0x0EB700), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_wifiButton, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_bleButton = lv_btn_create(ui_TabControlPad);
    lv_obj_set_width(ui_bleButton, 250);
    lv_obj_set_height(ui_bleButton, 60);
    lv_obj_set_x(ui_bleButton, 0);
    lv_obj_set_y(ui_bleButton, -30);
    lv_obj_set_align(ui_bleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_bleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_bleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_bleButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bleButton, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_bleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_bleButton, &ui_img_img_ble_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_bleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_bleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_bleButton, lv_color_hex(0x064E00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_bleButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_bleButton, lv_color_hex(0x0EB700), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_bleButton, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_Slider1 = lv_slider_create(ui_TabControlPad);
    lv_slider_set_value(ui_Slider1, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 250);
    lv_obj_set_height(ui_Slider1, 32);
    lv_obj_set_x(ui_Slider1, 0);
    lv_obj_set_y(ui_Slider1, 40);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x292829), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x94BEFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Slider1, &ui_img_img_light_png, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ButtonAutoScreenOff = lv_btn_create(ui_TabControlPad);
    lv_obj_set_width(ui_ButtonAutoScreenOff, 60);
    lv_obj_set_height(ui_ButtonAutoScreenOff, 60);
    lv_obj_set_x(ui_ButtonAutoScreenOff, 0);
    lv_obj_set_y(ui_ButtonAutoScreenOff, 110);
    lv_obj_set_align(ui_ButtonAutoScreenOff, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonAutoScreenOff, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonAutoScreenOff, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ButtonAutoScreenOff, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAutoScreenOff, lv_color_hex(0x2A2A2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ButtonAutoScreenOff, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_ButtonAutoScreenOff, &ui_img_img_autoscr_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_ButtonAutoScreenOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_ButtonAutoScreenOff, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ButtonAutoScreenOff, lv_color_hex(0x0EB700), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_ButtonAutoScreenOff, 255, LV_PART_MAIN | LV_STATE_CHECKED);


    ui_TabHome = lv_tabview_add_tab(ui_TabDesktop, "Home");
    lv_obj_set_style_bg_img_src(ui_TabHome, &ui_img_backgroundimg_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainTimeLabel = lv_label_create(ui_TabHome);
    lv_obj_set_width(ui_mainTimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mainTimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mainTimeLabel, 0);
    lv_obj_set_y(ui_mainTimeLabel, -120);
    lv_obj_set_align(ui_mainTimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mainTimeLabel, "00:00");
    lv_obj_set_style_text_color(ui_mainTimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mainTimeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mainTimeLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weekdayLabel = lv_label_create(ui_TabHome);
    lv_obj_set_width(ui_weekdayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weekdayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weekdayLabel, 32);
    lv_obj_set_y(ui_weekdayLabel, 100);
    lv_obj_set_align(ui_weekdayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weekdayLabel, "周五");
    lv_obj_set_style_text_color(ui_weekdayLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weekdayLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weekdayLabel, &ui_font_zhongwen30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weatherLabel2 = lv_label_create(ui_TabHome);
    lv_obj_set_width(ui_weatherLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weatherLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weatherLabel2, 98);
    lv_obj_set_y(ui_weatherLabel2, 100);
    lv_obj_set_align(ui_weatherLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weatherLabel2, "晴");
    lv_obj_set_style_text_color(ui_weatherLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_weatherLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weatherLabel2, &ui_font_zhongwen30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tempLabel = lv_label_create(ui_TabHome);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, 66);
    lv_obj_set_y(ui_tempLabel, 140);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "0℃");
    lv_obj_set_style_text_color(ui_tempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_tempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_tempLabel, &ui_font_wendu42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dataLabel = lv_label_create(ui_TabHome);
    lv_obj_set_width(ui_dataLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_dataLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_dataLabel, 0);
    lv_obj_set_y(ui_dataLabel, -80);
    lv_obj_set_align(ui_dataLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_dataLabel, "00/00");
    lv_obj_set_style_text_color(ui_dataLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dataLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dataLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabAPP = lv_tabview_add_tab(ui_TabDesktop, "APP");
    lv_obj_set_style_bg_img_src(ui_TabAPP, &ui_img_backgroundimg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgStateBar = lv_img_create(ui_Launch);
    lv_img_set_src(ui_ImgStateBar, &ui_img_img_statebar_png);
    lv_obj_set_width(ui_ImgStateBar, LV_SIZE_CONTENT);   /// 280
    lv_obj_set_height(ui_ImgStateBar, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_ImgStateBar, 0);
    lv_obj_set_y(ui_ImgStateBar, -164);
    lv_obj_set_align(ui_ImgStateBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImgStateBar, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImgStateBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_ImgStateBar, 255);

    ui_timeLabel = lv_label_create(ui_ImgStateBar);
    lv_obj_set_width(ui_timeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeLabel, -18);
    lv_obj_set_y(ui_timeLabel, -5);
    lv_obj_set_align(ui_timeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeLabel, "00:00");
    lv_obj_set_style_text_color(ui_timeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_timeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryIMG = lv_img_create(ui_ImgStateBar);
    lv_img_set_src(ui_batteryIMG, &ui_img_img_battery_png);
    lv_obj_set_width(ui_batteryIMG, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_batteryIMG, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_batteryIMG, 25);
    lv_obj_set_y(ui_batteryIMG, -5);
    lv_obj_set_align(ui_batteryIMG, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_batteryIMG, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_clear_flag(ui_batteryIMG, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_BatteryBar = lv_bar_create(ui_batteryIMG);
    lv_bar_set_value(ui_BatteryBar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_BatteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_BatteryBar, 18);
    lv_obj_set_height(ui_BatteryBar, 9);
    lv_obj_set_x(ui_BatteryBar, -2);
    lv_obj_set_y(ui_BatteryBar, 0);
    lv_obj_set_align(ui_BatteryBar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0x31404A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BatteryBar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BatteryBar, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BatteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    
    lv_obj_add_event_cb(ui_ButtonAutoScreenOff, ui_event_ButtonAutoScreenOff, LV_EVENT_ALL, NULL);

}

void ui_Launch_screen_destroy(void)
{
    if(ui_Launch) lv_obj_del(ui_Launch);

    // NULL screen variables
    ui_Launch = NULL;
    ui_TabDesktop = NULL;
    ui_TabControlPad = NULL;
    ui_wifiButton = NULL;
    ui_bleButton = NULL;
    ui_Slider1 = NULL;
    ui_ButtonAutoScreenOff = NULL;
    ui_TabHome = NULL;
    ui_mainTimeLabel = NULL;
    ui_weekdayLabel = NULL;
    ui_weatherLabel2 = NULL;
    ui_tempLabel = NULL;
    ui_dataLabel = NULL;
    ui_TabAPP = NULL;
    ui_ImgStateBar = NULL;
    ui_timeLabel = NULL;
    ui_batteryIMG = NULL;
    ui_BatteryBar = NULL;

}
