// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef _STUDY_UI_H
#define _STUDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_gongdeAPP.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_gongde01_png);    // assets/gongde01.png
LV_IMG_DECLARE(ui_img_gongde02_png);    // assets/gongde02.png

// FONTS
LV_FONT_DECLARE(ui_font_text20);
LV_FONT_DECLARE(ui_font_wendu42);
LV_FONT_DECLARE(ui_font_zhongwen30);

// UI INIT
void AppGongde_ui_init(void);
void AppGongde_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
