// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#include "../ui.h"
#include "nvs_flash.h"

char * gongde_namespace = "gongde"; 
nvs_handle_t gongde_handle;
char* gongde_key = "gongde_count";

lv_obj_t * ui_gongdeAPP = NULL;
lv_obj_t * ui_gongdeLabel = NULL;
// event funtions

uint32_t  gongde_count = 0;
char gongde_buf[11] = "0";          // 给LVGL标签用的字符串

void gongde_read (void){
	nvs_open(gongde_namespace,NVS_READWRITE,&gongde_handle);
	nvs_get_u32(gongde_handle,gongde_key,&gongde_count);
}
void gongde_write(void){
	nvs_set_u32(gongde_handle,gongde_key,gongde_count);
}

void addgongde(lv_event_t * e)
{
    // 计数+1
    gongde_count++;
    sprintf(gongde_buf, "%lu", gongde_count);
    lv_label_set_text(ui_gongdeLabel, gongde_buf);
}

void ui_event_gongdeAPP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        addgongde(e);
    }
}

// build funtions

void ui_gongdeAPP_screen_init(void)
{
    gongde_read();
    sprintf(gongde_buf, "%lu", gongde_count);


    ui_gongdeAPP = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_gongdeAPP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_gongdeAPP, &ui_img_gongde01_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_gongdeAPP, &ui_img_gongde02_png, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_gongdeLabel = lv_label_create(ui_gongdeAPP);
    lv_obj_set_width(ui_gongdeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_gongdeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_gongdeLabel, 175);
    lv_obj_set_y(ui_gongdeLabel, 40);
    lv_label_set_text(ui_gongdeLabel, gongde_buf);
    lv_obj_set_style_text_font(ui_gongdeLabel, &ui_font_zhongwen30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_gongdeAPP, ui_event_gongdeAPP, LV_EVENT_CLICKED, NULL);

}

void ui_gongdeAPP_screen_destroy(void)
{
    gongde_write();
    nvs_commit(gongde_handle);
    nvs_close(gongde_handle);
    if (ui_gongdeAPP) lv_obj_del_async(ui_gongdeAPP);
    ui_gongdeAPP = NULL;
    ui_gongdeLabel = NULL;

}
