// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef _STUDY_UI_H
#define _STUDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Launch.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_backgroundimg_png);    // assets/backgroundIMG.png
LV_IMG_DECLARE(ui_img_img_wifi_png);    // assets/IMG_Wifi.png
LV_IMG_DECLARE(ui_img_img_ble_png);    // assets/IMG_Ble.png
LV_IMG_DECLARE(ui_img_img_light_png);    // assets/IMG_Light.png
LV_IMG_DECLARE(ui_img_img_autoscr_png);    // assets/IMG_AutoScr.png
LV_IMG_DECLARE(ui_img_backgroundimg_1_png);    // assets/backgroundIMG_1.png
LV_IMG_DECLARE(ui_img_img_statebar_png);    // assets/IMG_StateBar.png
LV_IMG_DECLARE(ui_img_img_battery_png);    // assets/IMG_Battery.png
LV_IMG_DECLARE(ui_img_img_icon_defalut_png);

// FONTS
LV_FONT_DECLARE(ui_font_text20);
LV_FONT_DECLARE(ui_font_wendu42);
LV_FONT_DECLARE(ui_font_zhongwen30);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
