// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef _STUDY_UI_H
#define _STUDY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_img_wifi_png);    // assets/IMG_Wifi.png
LV_IMG_DECLARE(ui_img_img_time_png);    // assets/IMG_Time.png
LV_IMG_DECLARE(ui_img_img_ble_png);    // assets/IMG_Ble.png
LV_IMG_DECLARE(ui_img_img_res_png);    // assets/IMG_RES.png
LV_IMG_DECLARE(ui_img_img_ok_png);    // assets/IMG_OK.png

// FONTS
LV_FONT_DECLARE(ui_font_text20);
LV_FONT_DECLARE(ui_font_wendu42);
LV_FONT_DECLARE(ui_font_zhongwen30);

// UI INIT
void APPSettings_ui_init(void);
void APPSettings_ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
