// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ble_connect_start(lv_event_t * e);
void ScanWIFI(lv_event_t * e);
void connectWIFI(lv_event_t * e);
void TimeUpdata(lv_event_t * e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
