// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#include "ui.h"
#include "../WIFI/wifi_manager.h"
#include "../HTTP/HTTP.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "screens/ui_settingAPP.h"

#define MAX_WIFI_COUNT 20

static const char *TAG = "APPSeeting_Event";

static char selected_ssid[33] = {0};
static wifi_ap_record_t g_ap_list[MAX_WIFI_COUNT];
static uint16_t g_ap_count = 0;
static bool is_scanning = false; 
static bool is_connecting = false;
// 连接结果（由WiFi事件回调设置）
static bool wifi_connected_result = false;
static lv_timer_t *wifi_check_timer = NULL;


static void btn_del(lv_event_t *e)
{
	lv_obj_del(lv_event_get_target(e));
}

static void btn_create(const char *text)
{
    // ------------- 删掉所有 lvgl_lock / lvgl_unlock ----------------

    lv_obj_t *btn = lv_btn_create(lv_scr_act());
    lv_obj_set_style_radius(btn, 30, 0);
    lv_obj_set_size(btn, 150, 60);
    lv_obj_center(btn);
    lv_obj_set_style_text_color(btn, lv_color_hex(0xFFFFFF), 0);

    lv_obj_t *label = lv_label_create(btn);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_22, 0);
    lv_obj_center(label);

    lv_obj_add_event_cb(btn, btn_del, LV_EVENT_CLICKED, NULL);
}


// 异步回调包装函数：切LVGL线程弹窗
static void show_wifi_result_msg(void *param)
{
    bool ok = *(bool *)param;
    lv_obj_t *msg;  // 用来居中

    if(ok)
    {
        btn_create("OK");

    }
    else
    {
        btn_create("FAILED");

    }
    is_connecting = false;
    free(param);
}

//wifi状态回调（wifi_manager事件触发，不在LVGL线程）
static void wifi_state_callback(wifi_state_t state)
{
    if(!is_connecting) return; //非手动连接忽略通知

    bool *res = malloc(sizeof(bool));
    if(state == WIFI_STATE_CONNECTED)
    {
        *res = true;
    }
    else
    {
        *res = false;
    }
    //丢到LVGL主线程执行弹窗
    lv_async_call(show_wifi_result_msg, res);
}

//连接点击函数
void wifi_connect_click(lv_event_t *e)
{
    if (is_connecting)
    {
        btn_create("Pls Wait...");
        return;
    }

    const char *password = lv_textarea_get_text(ui_PasswordText);

    if (strlen(password) == 0)
    {
        btn_create("No Password");
        return;
    }

    static bool reg_cb = false;
    if(!reg_cb)
    {
        wifi_manager_set_state_cb(wifi_state_callback);
        reg_cb = true;
    }

    is_connecting = true;
    wifi_manager_save_credentials(selected_ssid,password);
    wifi_manager_connect(selected_ssid,password);

    btn_create("Connecting...");
}

static void wifi_item_click_cb(lv_event_t *e)
{
	lv_obj_t *btn = lv_event_get_target(e);
	char *ssid = (char *)lv_obj_get_user_data(btn);
	if (!ssid)
		return;

	strncpy(selected_ssid, ssid, sizeof(selected_ssid) - 1);

	lv_obj_clear_flag(ui_PanelWIFIConnect, LV_OBJ_FLAG_HIDDEN);
	lv_obj_move_foreground(ui_PanelWIFIConnect);

	lv_label_set_text(ui_LabelSSID, selected_ssid);
	lv_textarea_set_text(ui_PasswordText, "");
	lv_group_focus_obj(ui_PasswordText);
	lv_keyboard_set_textarea(ui_Keyboard1, ui_PasswordText);
}
static void ui_update_wifi_list(void *param)
{
    (void)param;  // 未使用

    // 检查面板是否还存在且有效
    if (!ui_PanelWLAN || !lv_obj_is_valid(ui_PanelWLAN)) {;
        ESP_LOGW(TAG, "ui_PanelWLAN 无效，放弃更新");
        return;
    }

    // 安全删除所有现有的 WiFi 按钮
    uint32_t child_cnt = lv_obj_get_child_cnt(ui_PanelWLAN);
    for (uint32_t i = 0; i < child_cnt; i++) {
        lv_obj_t *child = lv_obj_get_child(ui_PanelWLAN, 0);
        void *data = lv_obj_get_user_data(child);
        if (data) free(data);      // 释放之前保存的 ssid 字符串
        lv_obj_del(child);
    }

    // 根据全局 g_ap_list 重新创建按钮
    for (int i = 0; i < g_ap_count; i++) {
        const char *ssid = (const char *)g_ap_list[i].ssid;
        if (strlen(ssid) == 0) continue;   // 跳过隐藏 WiFi

        lv_obj_t *btn = lv_btn_create(ui_PanelWLAN);
        lv_obj_set_size(btn, 230, 50);
        lv_obj_set_style_radius(btn, 30, 0);
        lv_obj_set_style_bg_color(btn, lv_color_hex(0x949594), 0);

        lv_obj_t *label = lv_label_create(btn);
        lv_label_set_text_fmt(label, "%s", ssid);
        lv_obj_center(label);

        // 保存 ssid 字符串供点击回调使用
        char *ssid_copy = (char *)malloc(strlen(ssid) + 1);
        if (ssid_copy) {
            strcpy(ssid_copy, ssid);
            lv_obj_set_user_data(btn, ssid_copy);
            lv_obj_add_event_cb(btn, wifi_item_click_cb, LV_EVENT_CLICKED, NULL);
        }
    }

    // 可选：滚动到顶部
    lv_obj_scroll_to_y(ui_PanelWLAN, 0, LV_ANIM_OFF);
}
void wifi_scan_callback(int numbers, wifi_ap_record_t *ap_records)
{
    is_scanning = false;
    ESP_LOGI(TAG, "扫描完成！共 %d 个 WiFi", numbers);
    // 保存到全局数组（注意：ap_records 由 wifi_manager 分配，需要释放）
    g_ap_count = (numbers < MAX_WIFI_COUNT) ? numbers : MAX_WIFI_COUNT;
    memcpy(g_ap_list, ap_records, sizeof(wifi_ap_record_t) * g_ap_count);

    // 释放传入的内存（根据你的 wifi_manager 实现，可能需要用 free 或自定义释放）
    free(ap_records);   // 假设是 malloc 分配的

    // 将 UI 更新任务投递到 LVGL 任务
    lv_async_call(ui_update_wifi_list, NULL);
}

void ble_connect_start(lv_event_t * e)
{
	// Your code here
}

void ScanWIFI(lv_event_t * e)
{
	if (is_scanning) {
        btn_create("Wait...");
        return;
    }
	is_scanning = true;
	
	esp_err_t scan_ret = wifi_manager_scan(wifi_scan_callback);
    if (scan_ret == ESP_OK)
    {
        btn_create("Scanning...");
        ESP_LOGI(TAG, "WiFi 扫描任务已启动");
    }
    else
    {
		btn_create("try again");
        ESP_LOGE(TAG, "启动 WiFi 扫描失败");
		is_scanning = false;
    }
}

void connectWIFI(lv_event_t * e)
{
	wifi_connect_click(e);
}

void TimeUpdata(lv_event_t * e)
{
    
        if (wifi_manager_is_connect() == false) {
        btn_create("WIFI Pls");
        return;
    }
    // 一行搞定！
    if (location_http_init() == ESP_OK) {
        weather_http_init();
    }
    obtain_time();
    btn_create("OK");
}
