// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#include "../ui.h"
#include "../../WIFI/wifi_manager.h"
#include "esp_log.h"
static const char *TAG = "ui_settingAPP";

lv_obj_t * ui_settingAPP = NULL;
lv_obj_t * ui_PanelSettingList = NULL;
lv_obj_t * ui_settingWIFIButton = NULL;
lv_obj_t * ui_settingTimeButton = NULL;
lv_obj_t * ui_SettingBleButton = NULL;
lv_obj_t * ui_PanelWIFIScan = NULL;
lv_obj_t * ui_LabelWLAN = NULL;
lv_obj_t * ui_PanelWLAN = NULL;
lv_obj_t * ui_WLANResButton = NULL;
lv_obj_t * ui_PanelWIFIConnect = NULL;
lv_obj_t * ui_LabelSSID = NULL;
lv_obj_t * ui_PasswordText = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_WIFIConncetButton = NULL;
lv_obj_t * ui_PanelTime = NULL;
lv_obj_t * ui_TimeResButton = NULL;
// event funtions
void ui_event_settingAPP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_flag_modify(ui_PanelWIFIConnect, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PanelWIFIScan, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_PanelTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_settingWIFIButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PanelWIFIScan, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        
        // 1. 尝试分配大块内存来合并碎片
        void *p = heap_caps_malloc(16384, MALLOC_CAP_INTERNAL);
        if (p) free(p);

        // 2. 暂停调度器，再次分配-释放，促进碎片整理
        vTaskSuspendAll();
        p = heap_caps_malloc(16384, MALLOC_CAP_INTERNAL);
        if (p) free(p);
        xTaskResumeAll();

        // 3. 检查当前最大连续内存块
        size_t largest = heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL);
        size_t free_total = heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
        heap_caps_print_heap_info(MALLOC_CAP_INTERNAL);
        ESP_LOGI(TAG, "Free internal: %u bytes, largest block: %u bytes", free_total, largest); 
        // 内存足够，初始化 Wi-Fi
        wifi_manager_init();
    }
}

void ui_event_settingTimeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_PanelTime, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_SettingBleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ble_connect_start(e);
    }
}

void ui_event_WLANResButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ScanWIFI(e);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_PasswordText);
    }
}

void ui_event_WIFIConncetButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connectWIFI(e);
    }
}

void ui_event_TimeResButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        TimeUpdata(e);
    }
}

// build funtions

void ui_settingAPP_screen_init(void)
{
    ui_settingAPP = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settingAPP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingAPP, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingAPP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelSettingList = lv_obj_create(ui_settingAPP);
    lv_obj_set_width(ui_PanelSettingList, 360);
    lv_obj_set_height(ui_PanelSettingList, 360);
    lv_obj_set_x(ui_PanelSettingList, 1);
    lv_obj_set_y(ui_PanelSettingList, 0);
    lv_obj_set_align(ui_PanelSettingList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelSettingList, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelSettingList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PanelSettingList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelSettingList, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelSettingList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelSettingList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingWIFIButton = lv_btn_create(ui_PanelSettingList);
    lv_obj_set_width(ui_settingWIFIButton, 250);
    lv_obj_set_height(ui_settingWIFIButton, 65);
    lv_obj_set_x(ui_settingWIFIButton, 939);
    lv_obj_set_y(ui_settingWIFIButton, 2);
    lv_obj_set_align(ui_settingWIFIButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingWIFIButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingWIFIButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingWIFIButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_settingWIFIButton, &ui_img_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingTimeButton = lv_btn_create(ui_PanelSettingList);
    lv_obj_set_width(ui_settingTimeButton, 250);
    lv_obj_set_height(ui_settingTimeButton, 65);
    lv_obj_set_x(ui_settingTimeButton, 939);
    lv_obj_set_y(ui_settingTimeButton, 2);
    lv_obj_set_align(ui_settingTimeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingTimeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingTimeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settingTimeButton, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_settingTimeButton, &ui_img_img_time_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingBleButton = lv_btn_create(ui_PanelSettingList);
    lv_obj_set_width(ui_SettingBleButton, 250);
    lv_obj_set_height(ui_SettingBleButton, 60);
    lv_obj_set_x(ui_SettingBleButton, 0);
    lv_obj_set_y(ui_SettingBleButton, -30);
    lv_obj_set_align(ui_SettingBleButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingBleButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingBleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SettingBleButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_SettingBleButton, &ui_img_img_ble_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_SettingBleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_SettingBleButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_SettingBleButton, lv_color_hex(0x064E00), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_SettingBleButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_SettingBleButton, lv_color_hex(0x0EB700), LV_PART_MAIN | LV_STATE_USER_1);
    lv_obj_set_style_bg_opa(ui_SettingBleButton, 255, LV_PART_MAIN | LV_STATE_USER_1);

    ui_PanelWIFIScan = lv_obj_create(ui_settingAPP);
    lv_obj_set_width(ui_PanelWIFIScan, 360);
    lv_obj_set_height(ui_PanelWIFIScan, 360);
    lv_obj_set_align(ui_PanelWIFIScan, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelWIFIScan, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelWIFIScan, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelWIFIScan, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelWIFIScan, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWIFIScan, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWIFIScan, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWIFIScan, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelWLAN = lv_label_create(ui_PanelWIFIScan);
    lv_obj_set_width(ui_LabelWLAN, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelWLAN, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelWLAN, 2);
    lv_obj_set_y(ui_LabelWLAN, -148);
    lv_obj_set_align(ui_LabelWLAN, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelWLAN, "WLAN");
    lv_obj_set_style_text_color(ui_LabelWLAN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelWLAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelWLAN, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWLAN = lv_obj_create(ui_PanelWIFIScan);
    lv_obj_set_width(ui_PanelWLAN, 250);
    lv_obj_set_height(ui_PanelWLAN, 250);
    lv_obj_set_x(ui_PanelWLAN, -4);
    lv_obj_set_y(ui_PanelWLAN, 4);
    lv_obj_set_align(ui_PanelWLAN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelWLAN, LV_OBJ_FLAG_SCROLLABLE);   // 启用滚动
    lv_obj_set_style_radius(ui_PanelWLAN, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_scrollbar_mode(ui_PanelWLAN, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_layout(ui_PanelWLAN, LV_LAYOUT_FLEX);
    lv_obj_set_flex_flow(ui_PanelWLAN, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelWLAN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);

    ui_WLANResButton = lv_btn_create(ui_PanelWIFIScan);
    lv_obj_set_width(ui_WLANResButton, 50);
    lv_obj_set_height(ui_WLANResButton, 50);
    lv_obj_set_x(ui_WLANResButton, 3);
    lv_obj_set_y(ui_WLANResButton, 141);
    lv_obj_set_align(ui_WLANResButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WLANResButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WLANResButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WLANResButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WLANResButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WLANResButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WLANResButton, &ui_img_img_res_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WLANResButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WLANResButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelWIFIConnect = lv_obj_create(ui_settingAPP);
    lv_obj_set_width(ui_PanelWIFIConnect, 360);
    lv_obj_set_height(ui_PanelWIFIConnect, 360);
    lv_obj_set_align(ui_PanelWIFIConnect, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelWIFIConnect, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelWIFIConnect, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelWIFIConnect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelWIFIConnect, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelWIFIConnect, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelWIFIConnect, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelWIFIConnect, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSSID = lv_label_create(ui_PanelWIFIConnect);
    lv_obj_set_width(ui_LabelSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSSID, 2);
    lv_obj_set_y(ui_LabelSSID, -148);
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSSID, "SSID");
    lv_obj_set_style_text_color(ui_LabelSSID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSSID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSSID, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PasswordText = lv_textarea_create(ui_PanelWIFIConnect);
    lv_obj_set_width(ui_PasswordText, 266);
    lv_obj_set_height(ui_PasswordText, 63);
    lv_obj_set_x(ui_PasswordText, 1);
    lv_obj_set_y(ui_PasswordText, -21);
    lv_obj_set_align(ui_PasswordText, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PasswordText, "Placeholder...");
    lv_obj_set_style_radius(ui_PasswordText, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_PanelWIFIConnect);
    lv_obj_set_width(ui_Keyboard1, 364);
    lv_obj_set_height(ui_Keyboard1, 166);
    lv_obj_set_x(ui_Keyboard1, 31);
    lv_obj_set_y(ui_Keyboard1, 25);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Keyboard1, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIConncetButton = lv_btn_create(ui_PanelWIFIConnect);
    lv_obj_set_width(ui_WIFIConncetButton, 50);
    lv_obj_set_height(ui_WIFIConncetButton, 50);
    lv_obj_set_x(ui_WIFIConncetButton, 3);
    lv_obj_set_y(ui_WIFIConncetButton, 141);
    lv_obj_set_align(ui_WIFIConncetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WIFIConncetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WIFIConncetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WIFIConncetButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WIFIConncetButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFIConncetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_WIFIConncetButton, &ui_img_img_ok_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_WIFIConncetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_WIFIConncetButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTime = lv_obj_create(ui_settingAPP);
    lv_obj_set_width(ui_PanelTime, 360);
    lv_obj_set_height(ui_PanelTime, 360);
    lv_obj_set_align(ui_PanelTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PanelTime, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PanelTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelTime, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTime, lv_color_hex(0x414041), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeResButton = lv_btn_create(ui_PanelTime);
    lv_obj_set_width(ui_TimeResButton, 50);
    lv_obj_set_height(ui_TimeResButton, 50);
    lv_obj_set_x(ui_TimeResButton, 17);
    lv_obj_set_y(ui_TimeResButton, 7);
    lv_obj_set_align(ui_TimeResButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TimeResButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TimeResButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TimeResButton, 90, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TimeResButton, lv_color_hex(0x969696), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeResButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_TimeResButton, &ui_img_img_res_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_settingWIFIButton, ui_event_settingWIFIButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingTimeButton, ui_event_settingTimeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingBleButton, ui_event_SettingBleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WLANResButton, ui_event_WLANResButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WIFIConncetButton, ui_event_WIFIConncetButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TimeResButton, ui_event_TimeResButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingAPP, ui_event_settingAPP, LV_EVENT_ALL, NULL);

}

void ui_settingAPP_screen_destroy(void)
{
    if (ui_settingAPP) lv_obj_del_async(ui_settingAPP);

    // NULL screen variables
    ui_settingAPP = NULL;
    ui_PanelSettingList = NULL;
    ui_settingWIFIButton = NULL;
    ui_settingTimeButton = NULL;
    ui_SettingBleButton = NULL;
    ui_PanelWIFIScan = NULL;
    ui_LabelWLAN = NULL;
    ui_PanelWLAN = NULL;
    ui_WLANResButton = NULL;
    ui_PanelWIFIConnect = NULL;
    ui_LabelSSID = NULL;
    ui_PasswordText = NULL;
    ui_Keyboard1 = NULL;
    ui_WIFIConncetButton = NULL;
    ui_PanelTime = NULL;
    ui_TimeResButton = NULL;

}
