// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: study

#ifndef UI_SETTINGAPP_H
#define UI_SETTINGAPP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_settingAPP
extern void ui_settingAPP_screen_init(void);
extern void ui_settingAPP_screen_destroy(void);
extern void ui_event_settingAPP(lv_event_t * e);
extern lv_obj_t * ui_settingAPP;
extern lv_obj_t * ui_PanelSettingList;
extern void ui_event_settingWIFIButton(lv_event_t * e);
extern lv_obj_t * ui_settingWIFIButton;
extern void ui_event_settingTimeButton(lv_event_t * e);
extern lv_obj_t * ui_settingTimeButton;
extern void ui_event_SettingBleButton(lv_event_t * e);
extern lv_obj_t * ui_SettingBleButton;
extern lv_obj_t * ui_PanelWIFIScan;
extern lv_obj_t * ui_LabelWLAN;
extern lv_obj_t * ui_PanelWLAN;
extern void ui_event_WLANResButton(lv_event_t * e);
extern lv_obj_t * ui_WLANResButton;
extern lv_obj_t * ui_PanelWIFIConnect;
extern lv_obj_t * ui_LabelSSID;
extern lv_obj_t * ui_PasswordText;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_WIFIConncetButton(lv_event_t * e);
extern lv_obj_t * ui_WIFIConncetButton;
extern lv_obj_t * ui_PanelTime;
extern void ui_event_TimeResButton(lv_event_t * e);
extern lv_obj_t * ui_TimeResButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

